POST https://api.openai.com/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello world"}],
  "stream": true
}

### Moderation
POST https://api.openai.com/v1/moderations
Authorization: Bearer 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
Content-Type: application/json

{
  "input": "Test"
}